version: '3.8'

services:
  backend:
    build: ./backend
    container_name: bb-backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: bb-frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app

  database:
    image: mysql:8.0
    container_name: database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
    volumes:
      - bb-ecommerce-mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database

volumes:
  bb-ecommerce-mysql-data: