name: Docker CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: CI - Build & Test inside Docker
        run: |
          docker compose -f docker-compose.ci.yml up --build --abort-on-container-exit --exit-code-from frontend-test

      - name: CD - Deploy to server via SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/bb-ecommerce
            git pull origin main
            docker compose down
            docker compose up -d --build